[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.1.8"
thiserror = "2.0.18"

# [dev-dependencies]
# For testing later

# [[bin]]
# name = "pdf-table"
# path = "src/main.rs"
